# -*- coding: utf-8 -*-
# Filmek, sorozatok, játékok — kurált lista
# mezők: title, hu, type, canon, rel, y (in-universe év, BBY=negatív), era(opcionális override),
#        wook (Wookieepedia cikk cím a borítóhoz), desc, upcoming(opc), offtimeline(opc)

SCREEN = [
# ============ FILMEK (kánon) ============
dict(title="Star Wars: Episode I – The Phantom Menace", hu="Baljós árnyak", type="film", canon=True,
     rel="1999-05-19", y=-32, wook="Star Wars: Episode I The Phantom Menace",
     desc="A Skywalker-saga nyitánya: Qui-Gon Jinn és Obi-Wan Kenobi felfedezi a rabszolgasorban élő, kivételes erejű Anakin Skywalkert a Tatuinon, miközben a Kereskedelmi Szövetség blokád alá vonja a Naboo bolygót. A háttérben Darth Sidious szövi a Köztársaság bukásához vezető tervét."),
dict(title="Star Wars: Episode II – Attack of the Clones", hu="A klónok támadása", type="film", canon=True,
     rel="2002-05-16", y=-22, wook="Star Wars: Episode II Attack of the Clones",
     desc="Tíz évvel a naboo-i csata után a szeparatista mozgalom szakadás szélére sodorja a Köztársaságot. Anakin és Padmé között tiltott szerelem szövődik, Obi-Wan pedig egy titokban legyártott klónhadseregre bukkan — kitör a klónháború."),
dict(title="Star Wars: The Clone Wars (film)", hu="Star Wars: A klónok háborúja", type="film", canon=True,
     rel="2008-08-14", y=-21.9, wook="Star Wars: The Clone Wars (film)",
     desc="Az azonos című animációs sorozat mozis nyitánya: Anakin Skywalker megkapja első padawanját, Ahsoka Tanót, és együtt kell kiszabadítaniuk Jabba elrabolt fiát, hogy a Köztársaság megnyerje a huttok támogatását."),
dict(title="Star Wars: Episode III – Revenge of the Sith", hu="A Sith-ek bosszúja", type="film", canon=True,
     rel="2005-05-19", y=-19, era="fall", wook="Star Wars: Episode III Revenge of the Sith",
     desc="A klónháborúk lezárása és a saga tragikus fordulópontja: Palpatine kancellár magához ragadja a teljhatalmat, kiadja a 66-os parancsot, Anakin Skywalker pedig elbukik, és Darth Vaderként újjászületve a Birodalom szolgálatába áll."),
dict(title="Solo: A Star Wars Story", hu="Solo: Egy Star Wars-történet", type="film", canon=True,
     rel="2018-05-25", y=-10, era="reign", wook="Solo: A Star Wars Story",
     desc="A fiatal Han Solo első nagy kalandja: megismerkedik Csubakkával és Lando Calrissiannal, megszerzi az Ezeréves Sólymot, és teljesíti a hírhedt kesseli futamot — miközben a galaxis alvilágának kegyetlen törvényeit is megtanulja."),
dict(title="Rogue One: A Star Wars Story", hu="Zsivány Egyes: Egy Star Wars-történet", type="film", canon=True,
     rel="2016-12-16", y=-0.6, era="rebellion", wook="Rogue One: A Star Wars Story",
     desc="Közvetlenül az Egy új remény előtt játszódó háborús film: Jyn Erso és egy elszánt lázadó csapat öngyilkos küldetésre indul, hogy megszerezze a Halálcsillag terveit. Áldozatuk nélkül nem születhetne meg az új remény."),
dict(title="Star Wars: Episode IV – A New Hope", hu="Egy új remény", type="film", canon=True,
     rel="1977-05-25", y=0, era="rebellion", wook="Star Wars: Episode IV A New Hope",
     desc="Az 1977-es film, amellyel minden kezdődött: Luke Skywalker, egy tatuini parasztfiú két droiddal, egy csempésszel és egy öreg jedivel a Lázadó Szövetség oldalára áll, megmenti Leia hercegnőt, és felrobbantja a Birodalom Halálcsillagát."),
dict(title="Star Wars: Episode V – The Empire Strikes Back", hu="A Birodalom visszavág", type="film", canon=True,
     rel="1980-05-21", y=3, era="rebellion", wook="Star Wars: Episode V The Empire Strikes Back",
     desc="A saga legsötétebb fejezete: a Hoth-i vereség után Luke Yoda mesternél tanul a Dagobah-n, míg barátai Vader csapdájába sétálnak a Felhővárosban. A film a mozitörténet egyik leghíresebb fordulatával zárul: „Én vagyok az apád.”"),
dict(title="Star Wars: Episode VI – Return of the Jedi", hu="A Jedi visszatér", type="film", canon=True,
     rel="1983-05-25", y=4, era="rebellion", wook="Star Wars: Episode VI Return of the Jedi",
     desc="Az eredeti trilógia lezárása: Han Solo kiszabadul Jabba palotájából, az endori csatában elbukik a második Halálcsillag, Luke pedig megváltja apját — Anakin Skywalker végez az Uralkodóval, és beteljesíti a próféciát."),
dict(title="Star Wars: The Mandalorian and Grogu", hu="A Mandalóri és Grogu", type="film", canon=True,
     rel="2026-05-22", y=12, era="newrepublic", wook="The Mandalorian and Grogu",
     desc="A Star Wars 2026-ban visszatért a mozikba: Din Djarin és Grogu közös kalandja a sorozat harmadik évada után játszódik. Az Új Köztársaság megbízásából a birodalmi maradványok ellen harcolnak, útjuk során pedig ismét próbára tétetik a fogadott apa és fia közti kötelék."),
dict(title="Star Wars: Episode VII – The Force Awakens", hu="Az ébredő Erő", type="film", canon=True,
     rel="2015-12-18", y=34, era="firstorder", wook="Star Wars: Episode VII The Force Awakens",
     desc="Harminc évvel az endori csata után a Birodalom hamvaiból kiemelkedő Első Rend fenyegeti a galaxist. A jakkui guberáló Rey és a dezertőr rohamosztagos Finn az Ellenállás oldalán sodródik a konfliktusba — és megkezdődik Luke Skywalker keresése."),
dict(title="Star Wars: Episode VIII – The Last Jedi", hu="Az utolsó Jedik", type="film", canon=True,
     rel="2017-12-15", y=34.2, era="firstorder", wook="Star Wars: Episode VIII The Last Jedi",
     desc="Rey a remeteként élő Luke Skywalkert győzködi, hogy térjen vissza, miközben az Első Rend bekeríti a menekülő Ellenállást. A film a jedi örökség, a kudarc és az áldozat témáit boncolgatja, és Luke utolsó, legendás kiállásával zárul."),
dict(title="Star Wars: Episode IX – The Rise of Skywalker", hu="Skywalker kora", type="film", canon=True,
     rel="2019-12-20", y=35, era="firstorder", wook="Star Wars: Episode IX The Rise of Skywalker",
     desc="A Skywalker-saga fináléja: a holtából visszatért Palpatine végső flottája ellen az egész galaxis összefog. Rey szembenéz származása titkával, Ben Solo megváltást nyer, a Sith-ek pedig örökre elbuknak az exegoli csatában."),
dict(title="Star Wars: Starfighter", hu=None, type="film", canon=True, upcoming=True,
     rel="2027-05-27", y=40, era="newjedi", wook="Star Wars: Starfighter",
     desc="Shawn Levy készülő mozifilmje Ryan Goslinggal a főszerepben, amely a Skywalker kora után öt évvel játszódik — a mozikba 2027 májusában érkezik. Az Új Jedi Rend korszakának első nagy vászonra szánt kalandja."),
# ============ FILMEK / TV-FILMEK (Legends) ============
dict(title="The Star Wars Holiday Special", hu="Star Wars ünnepi különkiadás", type="tvfilm", canon=False,
     rel="1978-11-17", y=1, era="rebellion", wook="The Star Wars Holiday Special",
     desc="A hírhedt 1978-as tévés különkiadás: Han Solo igyekszik hazajuttatni Csubakkát a Kashyyykra, hogy családjával ünnepelhesse az Életnapot. Ma már inkább kultikus kuriózum — itt tűnt fel először Boba Fett, egy animációs betétben."),
dict(title="Caravan of Courage: An Ewok Adventure", hu="Az ewokok kalandjai", type="tvfilm", canon=False,
     rel="1984-11-25", y=3.2, era="rebellion", wook="Caravan of Courage: An Ewok Adventure",
     desc="Legends tévéfilm az Endor holdján: két hajótörött gyerek, Mace és Cindel az ewokok segítségével vág neki a vadonnak, hogy kiszabadítsa szüleiket az óriás Gorax karmai közül."),
dict(title="Ewoks: The Battle for Endor", hu="Ewokok: Csata Endor bolygón", type="tvfilm", canon=False,
     rel="1985-11-24", y=3.5, era="rebellion", wook="Ewoks: The Battle for Endor",
     desc="Az ewok-tévéfilmek folytatása, sötétebb tónusban: Cindel és Wicket a marauderek támadása után egy remete és egy ewok falu maradékával veszi fel a harcot Terak király és Charal boszorkány ellen."),
# ============ ÉLŐSZEREPLŐS SOROZATOK ============
dict(title="The Acolyte", hu="Az akolitus", type="liveaction", canon=True,
     rel="2024-06-04", y=-132, era="highrepublic", wook="The Acolyte",
     desc="A Főkorszak alkonyán, száz évvel a Baljós árnyak előtt játszódó krimi-sorozat: egy jedi mester és egykori padawanja veszélyes gyilkossági ügyben nyomoz, amely a Sith-ek árnyékába vezet. Egy évad készült belőle."),
dict(title="Obi-Wan Kenobi", hu="Obi-Wan Kenobi", type="liveaction", canon=True,
     rel="2022-05-27", y=-9, era="reign", wook="Obi-Wan Kenobi (television series)",
     desc="Ewan McGregor visszatérése a szerepéhez: a Tatuinon remetéskedő Obi-Wannak el kell hagynia rejtekét, hogy megmentse az elrabolt gyermek Leiát — útja során pedig szembekerül egykori tanítványával, Darth Vaderrel és az inkvizítorokkal."),
dict(title="Andor", hu="Andor", type="liveaction", canon=True,
     rel="2022-09-21", y=-4, era="rebellion", wook="Andor (television series)",
     desc="A kritikusok által legjobban értékelt Star Wars-sorozat: Cassian Andor útja a kisstílű tolvajtól a Zsivány Egyes elszánt kéméig. Felnőtt hangvételű politikai thriller a születő Lázadásról, a birodalmi elnyomás gépezetéről — két évadon át, egészen a Rogue One küszöbéig."),
dict(title="The Mandalorian", hu="A Mandalóri", type="liveaction", canon=True,
     rel="2019-11-12", y=9, era="newrepublic", wook="The Mandalorian",
     desc="A sorozat, amely új korszakot nyitott a Star Warsban: a magányos mandalóri fejvadász, Din Djarin egy rejtélyes, Erő-érzékeny gyermeket — Grogut — vesz védelmébe a Birodalom maradványai elől. Három évad, két Emmy-díj és a Baby Yoda-jelenség."),
dict(title="The Book of Boba Fett", hu="Boba Fett könyve", type="liveaction", canon=True,
     rel="2021-12-29", y=9.4, era="newrepublic", wook="The Book of Boba Fett",
     desc="A sarlaccból kimenekült legendás fejvadász, Boba Fett átveszi Jabba egykori bűnbirodalmát a Tatuinon. A sorozat feltárja, hogyan élte túl a Jedi visszatér eseményeit, és hogyan vált a tuszkenek fogságából a Mos Espa-i alvilág daimjójává."),
dict(title="Star Wars: Skeleton Crew", hu="Star Wars: Csontvázlegénység", type="liveaction", canon=True,
     rel="2024-12-02", y=9.45, era="newrepublic", wook="Star Wars: Skeleton Crew",
     desc="Amblin-hangulatú kalandsorozat: négy gyerek egy rejtélyes űrhajóval véletlenül elhagyja eldugott otthonbolygóját, és a galaxis kalózoktól hemzsegő szegletében próbál hazatalálni — a Jude Law játszotta talányos Erő-használó segítségével."),
dict(title="Ahsoka", hu="Ahsoka", type="liveaction", canon=True,
     rel="2023-08-22", y=11, era="newrepublic", wook="Ahsoka (television series)",
     desc="Ahsoka Tano a Lázadók történetét folytatva Thrawn főadmirális visszatérésének nyomába ered, és egy másik galaxisba is átkel Sabine Wrennel és Ezra Bridgerrel. A második évad várhatóan 2026 végén / 2027 elején érkezik a Disney+-ra."),
# ============ ANIMÁCIÓS SOROZATOK (kánon) ============
dict(title="Star Wars: Young Jedi Adventures", hu="Star Wars: Fiatal jedik kalandjai", type="animseries", canon=True,
     rel="2023-05-04", y=-231, era="highrepublic", wook="Star Wars: Young Jedi Adventures",
     desc="A legfiatalabbaknak szóló animációs sorozat a Főkorszak idejéből: jedi növendékek — köztük Kai Brightstar — tanulják az Erő és a barátság leckéit a Tenoo bolygón. Az első Star Wars-sorozat, amely kifejezetten óvodásoknak készült."),
dict(title="Star Wars: Tales of the Jedi", hu="Star Wars: Jedi-történetek", type="animseries", canon=True,
     rel="2022-10-26", y=-22.4, wook="Star Wars: Tales of the Jedi (television series)",
     desc="Dave Filoni antológiája hat rövid, gyönyörűen animált epizódban: Ahsoka Tano életének állomásai és Dooku gróf lassú elsötétedése — két sors, amely a jedi rend tündöklését és vakságát tükrözi."),
dict(title="Star Wars: The Clone Wars", hu="Star Wars: A klónok háborúja", type="animseries", canon=True,
     rel="2008-10-03", y=-21.8, wook="Star Wars: The Clone Wars",
     desc="A modern Star Wars-kánon gerince, hét évadon át: Anakin, Obi-Wan és Ahsoka kalandjai a klónháborúk frontjain. A sorozat tette igazán mélyé Anakin bukását, és olyan ikonikus karaktereket adott a sagának, mint Ahsoka Tano, Rex kapitány vagy a visszatérő Maul."),
dict(title="Star Wars: The Bad Batch", hu="Star Wars: A Rossz Osztag", type="animseries", canon=True,
     rel="2021-05-04", y=-18.9, era="reign", wook="Star Wars: The Bad Batch",
     desc="A Klónok háborúja folytatása a Birodalom hajnalán: a 99-es kísérleti klónosztag — a Rossz Osztag — szembefordul az új renddel, és a kis Omega védelmezőjeként menekül a galaxison át. Három évadon keresztül futott."),
dict(title="Star Wars: Tales of the Empire", hu="Star Wars: Birodalmi történetek", type="animseries", canon=True,
     rel="2024-05-04", y=-18.5, era="reign", wook="Star Wars: Tales of the Empire",
     desc="A Tales-antológia második része a sötét oldal felől: Morgan Elsbeth útja a nightsister-mészárlástól Thrawn szolgálatáig, valamint Barriss Offee sorsa az inkvizítorok között — hat epizódban."),
dict(title="Star Wars: Maul – Shadow Lord", hu="Star Wars: Maul – Az árnyak ura", type="animseries", canon=True,
     rel="2026-04-06", y=-18.2, era="reign", wook="Maul - Shadow Lord",
     desc="2026 áprilisában debütált animációs sorozat: egy évvel a Sith-ek bosszúja után Maul a birodalmi éra alvilágában építi saját árnybirodalmát, miközben tanítványt fogad. Sam Witwer ikonikus hangjával — a második évad már be is lett jelentve."),
dict(title="Star Wars: Tales of the Underworld", hu="Star Wars: Alvilági történetek", type="animseries", canon=True,
     rel="2025-05-04", y=-17.5, era="reign", wook="Star Wars: Tales of the Underworld",
     desc="A Tales-antológia harmadik felvonása a galaxis alvilágáról: Asajj Ventress új esélyt kap az életre, Cad Bane pedig a múltjával számol el. Hat epizód, 2025 májusától."),
dict(title="Star Wars Rebels", hu="Star Wars: Lázadók", type="animseries", canon=True,
     rel="2014-10-03", y=-5, era="rebellion", wook="Star Wars Rebels",
     desc="A Szellem hajó legénysége — Hera, Kanan, Ezra, Sabine, Zeb és Chopper — a formálódó Lázadás egyik első sejtje. Négy évadon át ível a történetük a Birodalom árnyékától a lothali felszabadításig, olyan emlékezetes ellenfelekkel, mint Thrawn főadmirális."),
dict(title="Star Wars Resistance", hu="Star Wars: Ellenállás", type="animseries", canon=True,
     rel="2018-10-07", y=33.8, era="firstorder", wook="Star Wars Resistance",
     desc="Az ébredő Erő előestéjén játszódó animációs sorozat: Kazuda Xiono, az Ellenállás újdonsült kéme egy óceáni üzemanyagtöltő állomáson, a Colossuson figyeli az Első Rend térnyerését. Két évadot élt meg, anime-ihlette látványvilággal."),
# ============ ANIMÁCIÓS SOROZATOK (Legends) ============
dict(title="Star Wars: Clone Wars (2003)", hu="Klónok háborúja (2003)", type="animseries", canon=False,
     rel="2003-11-07", y=-21.7, wook="Star Wars: Clone Wars",
     desc="Genndy Tartakovsky Emmy-díjas, stilizált mikroepizód-sorozata a klónháborúkról — a Legends-kontinuitás része. Itt debütált Grievous tábornok, és itt vált legendássá Mace Windu és a jedik szinte szuperhősi ábrázolása."),
dict(title="Star Wars: Droids", hu="Star Wars: Droidok", type="animseries", canon=False,
     rel="1985-09-07", y=-15, era="reign", wook="Star Wars: Droids",
     desc="1985-ös rajzfilmsorozat R2-D2 és C-3PO korai kalandjairól, még az Egy új remény előtt: a két droid gazdáról gazdára vándorolva keveredik csempészek, fejvadászok és birodalmiak ügyeibe."),
dict(title="Star Wars: Ewoks", hu="Star Wars: Ewokok", type="animseries", canon=False,
     rel="1985-09-07", y=3.1, era="rebellion", wook="Star Wars: Ewoks",
     desc="A Droids testvérsorozata: Wicket és az ewokok mesés kalandjai az Endor erdőholdján, még a Jedi visszatér eseményei előtt. Két évadnyi könnyed, gyerekeknek szóló Legends-történet."),
# ============ MINISOROZAT ============
dict(title="Star Wars: Forces of Destiny", hu="Star Wars: A végzet erői", type="miniseries", canon=True,
     rel="2017-07-03", y=0.1, era="rebellion", wook="Star Wars Forces of Destiny",
     desc="Rövid, 2-3 perces animációs epizódok a saga hősnőiről: Rey, Jyn, Sabine, Leia, Ahsoka és Padmé kisebb-nagyobb hőstettei a filmek és sorozatok jelenetei között. A korszakokon átívelő antológia a Lázadás korától a sequelekig ugrál."),
# ============ VIDEÓJÁTÉKOK (kánon) ============
dict(title="Star Wars Eclipse", hu=None, type="game", canon=True, upcoming=True,
     rel=None, y=-230, era="highrepublic", wook="Star Wars Eclipse",
     desc="A Quantic Dream (Detroit: Become Human) fejlesztés alatt álló, narratív akció-kalandjátéka a Főkorszak idején — az első videójáték, amely a High Republic érában játszódik. Megjelenési dátuma még nincs."),
dict(title="Star Wars Zero Company", hu=None, type="game", canon=True, upcoming=True,
     rel="2026-08-27", y=-20, wook="Star Wars Zero Company",
     desc="A Bit Reactor és a Respawn körökre osztott taktikai játéka (az XCOM veteránjaitól): a klónháborúk végnapjaiban egy elit különítmény, a Zero Company vezetését vesszük át. 2026. augusztus 27-én jelenik meg."),
dict(title="Star Wars Jedi: Fallen Order", hu=None, type="game", canon=True,
     rel="2019-11-15", y=-14, era="reign", wook="Star Wars Jedi: Fallen Order",
     desc="A Respawn akció-kalandjátéka: Cal Kestis, a 66-os parancsot túlélő fiatal padawan a Birodalom inkvizítorai elől menekülve próbálja újjáéleszteni a jedi rend reményét. A modern Star Wars-játékok egyik legnagyobb sikere."),
dict(title="Star Wars Jedi: Survivor", hu=None, type="game", canon=True,
     rel="2023-04-28", y=-9, era="reign", wook="Star Wars Jedi: Survivor",
     desc="A Fallen Order folytatása öt évvel később: az érett jedivé váló Cal Kestis a Birodalom szorításában egy rejtett menedék, Tanalorr titkát kutatja. Nagyobb világok, mélyebb harcrendszer és egy megrázó középső fejezet."),
dict(title="Star Wars: Beyond Victory – A Mixed Reality Playset", hu=None, type="game", canon=True,
     rel="2025-10-07", y=-10, era="reign", wook="Star Wars: Beyond Victory - A Mixed Reality Playset",
     desc="Az ILM kevertvalóság-kísérlete Meta Quest platformra: egy fogatverseny-történet a Birodalom korából, amelyben a játéktér a nappalinkba költözik. 2025 októberében jelent meg."),
dict(title="Vader Immortal: A Star Wars VR Series", hu=None, type="game", canon=True,
     rel="2019-05-21", y=-1, era="rebellion", wook="Vader Immortal: A Star Wars VR Series",
     desc="Háromrészes VR-kaland: egy csempész a Mustafaron, Darth Vader erődjében találja magát, ahol a Sith nagyúr ősi ereklyék felkutatására kényszeríti. Az egyik legjobban sikerült Star Wars VR-élmény, David S. Goyer tollából."),
dict(title="Star Wars Battlefront (2015)", hu=None, type="game", canon=True,
     rel="2015-11-17", y=-0.4, era="rebellion", wook="Star Wars Battlefront (DICE)",
     desc="A DICE látványos többjátékos lövöldéje a galaktikus polgárháború ikonikus csatateréin, a Hoth-tól az Endorig. Kampányt nem kapott, de a Battle of Jakku DLC-vel a kánon egyik sorsdöntő csatáját is megidézte."),
dict(title="Star Wars Outlaws", hu=None, type="game", canon=True,
     rel="2024-08-30", y=3.3, era="rebellion", wook="Star Wars Outlaws",
     desc="Az első nyílt világú Star Wars-játék a Ubisofttól: a vagány tolvaj, Kay Vess és társa, Nix a galaxis bűnszindikátusai — köztük a Zerek Besh — között lavírozva vállalja el élete legnagyobb balhéját, a Birodalom visszavág és a Jedi visszatér közti időszakban."),
dict(title="Star Wars Battlefront II (2017)", hu=None, type="game", canon=True,
     rel="2017-11-09", y=4.2, era="newrepublic", wook="Star Wars Battlefront II",
     desc="A folytatás már kánon kampányt is kapott: Iden Versio, az Inferno osztag parancsnoka az endori vereség után kérdőjelezi meg a Birodalom ügyét. A többjátékos mód mindhárom filmkorszak hőseit és csatatereit felvonultatja."),
dict(title="Star Wars: Squadrons", hu=None, type="game", canon=True,
     rel="2020-10-02", y=4.6, era="newrepublic", wook="Star Wars: Squadrons",
     desc="Pilótafülke-szimuláció a Jedi visszatér utáni hónapokból: az Új Köztársaság Vanguard és a Birodalom Titan századának pilótájaként éljük át a galaktikus polgárháború utolsó nagy űrcsatáit — akár VR-ben is."),
dict(title="Star Wars: Uprising", hu=None, type="game", canon=True,
     rel="2015-09-10", y=4.8, era="newrepublic", wook="Star Wars: Uprising",
     desc="Mobil akció-RPG az endori csata utáni hónapokból: az Anoat szektort lezáró birodalmi „Vasblokád” ellen szerveződő felkelést követi — az első játékok egyike, amely az új kánon űrét töltötte ki. Szerverei 2016-ban leálltak."),
dict(title="Star Wars: Galactic Racer", hu=None, type="game", canon=True, upcoming=True,
     rel="2026-10-06", y=5.2, era="newrepublic", wook="Star Wars: Galactic Racer",
     desc="Készülő versenyjáték, amely a fogatversenyzés adrenalinját hozza vissza a Star Warsba az Új Köztársaság korában — 2026 októberében érkezik."),
dict(title="Star Wars: Hunters", hu=None, type="game", canon=True,
     rel="2024-06-04", y=9.2, era="newrepublic", wook="Star Wars: Hunters",
     desc="Arénaharc-játék a Birodalom bukása utáni évekből: a Vespaara bolygó Arénájában a galaxis minden tájáról érkező vadászok — birodalmi veteránok, wookiee harcosok, droidok — csapnak össze a nézők szórakoztatására."),
dict(title="Star Wars: Tales from the Galaxy's Edge", hu=None, type="game", canon=True,
     rel="2020-11-19", y=34.3, era="firstorder", wook="Star Wars: Tales from the Galaxy's Edge",
     desc="VR-kalandjáték a Batuu bolygón, a sequel-trilógia idején: egy droidtechnikusként keveredünk a Fekete Csúcs előőrs csempészei, ellenállói és az Első Rend járőrei közé. A Last Call kiegészítővel vált teljessé."),
]

# ============ IDŐVONALON KÍVÜL ============
OFFTIMELINE = [
dict(title="Star Wars: Visions", hu="Star Wars: Látomások", type="animseries", canon=True,
     rel="2021-09-22", y=None, era="outside", wook="Star Wars: Visions",
     desc="Antológia, amelyben a világ legjobb animációs stúdiói — az anime nagyjaitól az Aardmanig — mesélnek szabadon, a kánon kötöttségei nélkül Star Wars-történeteket. Három kötete jelent meg (2021, 2023, 2025), a kritikusok kedvence."),
dict(title="Star Wars: Galaxy of Adventures", hu="Star Wars: Kalandok galaxisa", type="miniseries", canon=True,
     rel="2018-11-30", y=None, era="outside", wook="Star Wars Galaxy of Adventures",
     desc="Percnyi hosszúságú, dinamikus websorozat, amely a saga ikonikus pillanatait meséli újra fiatal közönségnek, stilizált animációval — Luke-tól Vaderen át Reyig."),
]
