# -*- coding: utf-8 -*-
# Regények és képregények — kurált lista

NOVELS = [
# ---- High Republic / Főkorszak ----
dict(title="The High Republic: Path of Deceit", hu=None, type="novel", canon=True, rel="2022-10-04", y=-382,
     wook="The High Republic: Path of Deceit",
     desc="A Főkorszak II. fázisának nyitánya, 150 évvel a Fényes Köztársaság aranykora előtt: a Nyitott Kéz szektája köré épülő ifjúsági regény, amelyben feltűnik a későbbi nagy ellenség, a Nihil gyökere."),
dict(title="The High Republic: Convergence", hu=None, type="novel", canon=True, rel="2022-11-22", y=-381.9,
     wook="The High Republic: Convergence",
     desc="Két háborúban álló bolygó, Eiram és E'ronoh viszálya fenyegeti a Külső Perem békéjét — a jedik közvetíteni próbálnak, miközben a háttérben ismeretlen erők szítják a konfliktust."),
dict(title="The High Republic: Cataclysm", hu=None, type="novel", canon=True, rel="2023-04-04", y=-381.6,
     wook="The High Republic: Cataclysm",
     desc="Az Eiram és E'ronoh körüli válság robbanásig jut: a II. fázis felnőtt regényeinek csúcspontja, amelyben a Nyitott Kéz igazi arca is lelepleződik."),
dict(title="The High Republic: Path of Vengeance", hu=None, type="novel", canon=True, rel="2023-05-02", y=-381.55,
     wook="The High Republic: Path of Vengeance",
     desc="A II. fázis záró ifjúsági regénye: Marda Ro útja a hitbuzgó követőből a Nameless-lények prófétájává — a Nihil és a jedik évszázados konfliktusának eredettörténete."),
dict(title="The High Republic: Light of the Jedi", hu="Fényes Köztársaság: A jedik fénye", type="novel", canon=True, rel="2021-01-05", y=-232,
     wook="The High Republic: Light of the Jedi",
     desc="A High Republic-korszak nagyszabású nyitánya: a Legacy Run katasztrófája után a jedik a Köztársaság aranykorának csúcsán néznek szembe egy új, kiszámíthatatlan ellenséggel — Marchion Ro Nihiljével."),
dict(title="The High Republic: Into the Dark", hu=None, type="novel", canon=True, rel="2021-02-02", y=-231.9,
     wook="The High Republic: Into the Dark",
     desc="Reath Silas, a könyvmoly padawan első igazi kalandja: egy elhagyatott űrállomáson ősi sötétség ébredezik. Claudia Gray ifjúsági regénye az I. fázis egyik legjobbja."),
dict(title="The High Republic: The Rising Storm", hu=None, type="novel", canon=True, rel="2021-06-29", y=-231,
     wook="The High Republic: The Rising Storm",
     desc="A Köztársaság Valo bolygón rendezett ünnepélyes seregszemléjére lesújt a Nihil — a korszak egyik legdrámaibb fordulópontja, amely után semmi sem marad a régiben."),
dict(title="The High Republic: Out of the Shadows", hu=None, type="novel", canon=True, rel="2021-07-27", y=-230.9,
     wook="The High Republic: Out of the Shadows",
     desc="Ifjúsági regény a Valo utáni hónapokból: egy fuvarozópilóta lány a jedik és a Nihil hatalmi játszmáinak kereszttüzébe kerül."),
dict(title="The High Republic: The Fallen Star", hu=None, type="novel", canon=True, rel="2022-01-04", y=-230,
     wook="The High Republic: The Fallen Star",
     desc="Az I. fázis megrendítő csúcspontja: a Nihil végrehajtja legmerészebb csapását a jedik büszkesége, a Csillagfény Jelzőfény űrállomás ellen. Claudia Gray regénye a korszak legsötétebb órája."),
dict(title="The High Republic: Midnight Horizon", hu=None, type="novel", canon=True, rel="2022-02-01", y=-229.9,
     wook="The High Republic: Midnight Horizon",
     desc="A Csillagfény bukása után a Corellián nyomoz két jedi mester és padawanjaik — ifjúsági regény, amely a gyász és az újrakezdés hangján zárja az I. fázist."),
dict(title="The High Republic: The Eye of Darkness", hu=None, type="novel", canon=True, rel="2023-11-14", y=-228,
     wook="The High Republic: The Eye of Darkness",
     desc="A III. fázis nyitánya: a Nihil Okklúziós Zónája mögött rekedt világok és jedik küzdelme — a galaxis kettészakadt, és Marchion Ro hatalma csúcsán áll."),
dict(title="The High Republic: Defy the Storm", hu=None, type="novel", canon=True, rel="2024-03-05", y=-227.9,
     wook="The High Republic: Defy the Storm",
     desc="Ifjúsági regény az Okklúziós Zóna széléről: régi ismerősök fognak össze, hogy áttörjék a Nihil blokádját."),
dict(title="The High Republic: Temptation of the Force", hu=None, type="novel", canon=True, rel="2024-06-11", y=-227.8,
     wook="The High Republic: Temptation of the Force",
     desc="Elzar Mann és Avar Kriss végre együtt veszi fel a harcot a Nihillel — miközben a Nameless-lények titka egyre nyugtalanítóbb mélységeket tár fel."),
dict(title="The High Republic: Tears of the Nameless", hu=None, type="novel", canon=True, rel="2024-09-24", y=-227.7,
     wook="The High Republic: Tears of the Nameless",
     desc="Ifjúsági regény, amely a Nameless-lények eredetének nyomába ered — miközben a jedik rendje a teljes összeomlás szélén táncol."),
dict(title="The High Republic: Into the Light", hu=None, type="novel", canon=True, rel="2025-04-01", y=-227.6,
     wook="The High Republic: Into the Light",
     desc="A III. fázis utolsó előtti felnőtt regénye: a jedik ellentámadásba lendülnek, hogy visszafoglalják az elzárt zónát és leszámoljanak a Nihillel."),
dict(title="The High Republic: Trials of the Jedi", hu=None, type="novel", canon=True, rel="2025-06-17", y=-227.5,
     wook="The High Republic: Trials of the Jedi",
     desc="Charles Soule regénye, a teljes High Republic-kezdeményezés 2025-ös nagy fináléja: a jedik utolsó, mindent eldöntő összecsapása Marchion Róval és a Nameless-lényekkel."),
dict(title="The Acolyte: Wayseeker", hu=None, type="novel", canon=True, rel="2025-05-06", y=-160,
     wook="The Acolyte: Wayseeker",
     desc="Az akolitus sorozathoz kapcsolódó regény Vernestra Rwoh-ról: a jedi mester évtizedekkel a sorozat eseményei előtt egy útkereső küldetésen szembesül a rend korlátaival."),
dict(title="The Acolyte: The Crystal Crown", hu=None, type="novel", canon=True, rel="2025-07-29", y=-134,
     wook="The Acolyte: The Crystal Crown",
     desc="Az akolitus előzményregénye: Osha és Mae történetéhez kapcsolódó szálak a Főkorszak alkonyán."),
# ---- Fall of the Jedi ----
dict(title="Padawan", hu=None, type="novel", canon=True, rel="2022-07-26", y=-41,
     wook="Padawan (novel)",
     desc="A tinédzser Obi-Wan Kenobi első önálló kalandja: mesterétől elszakadva egy rejtélyes bolygón, felnőttek nélkül élő fiatalok között kell megtalálnia, mit jelent jedinek lenni."),
dict(title="Master & Apprentice", hu="Mester és tanítvány", type="novel", canon=True, rel="2019-04-16", y=-40,
     wook="Master & Apprentice",
     desc="Claudia Gray regénye Qui-Gon Jinn és a fiatal Obi-Wan feszültségekkel teli kapcsolatáról: egy diplomáciai küldetés a Pijal holdján próbára teszi a mester és padawanja közti bizalmat — és felsejlenek az ősi jedi próféciák is."),
dict(title="The Living Force", hu=None, type="novel", canon=True, rel="2024-04-09", y=-33,
     wook="The Living Force",
     desc="John Jackson Miller regénye egy évvel a Baljós árnyak előtt: a teljes Jedi Tanács — mind a tizenkét mester — közösen száll ki a terepre, hogy megmentsen egy haldokló kolóniát."),
dict(title="Queen's Peril", hu=None, type="novel", canon=True, rel="2020-06-02", y=-32.1,
     wook="Queen's Peril",
     desc="A frissen megválasztott, tizennégy éves Amidala királynő összeállítja szolgálólányai titkos csapatát — a Baljós árnyak eseményei alatt és előtt játszódó ifjúsági regény."),
dict(title="Mace Windu: The Glass Abyss", hu=None, type="novel", canon=True, rel="2024-10-15", y=-31.5,
     wook="Mace Windu: The Glass Abyss",
     desc="Steven Barnes regénye: Qui-Gon halála után Mace Windu egy üvegsivatagos bűnvárosba utazik, hogy teljesítse elesett barátja utolsó kérését — közben saját harcos-filozófiájával is szembenéz."),
dict(title="Queen's Shadow", hu="A királynő árnyéka", type="novel", canon=True, rel="2019-03-05", y=-28,
     wook="Queen's Shadow",
     desc="Padmé Amidala a királynői trónról a szenátusba lép át — E. K. Johnston regénye a szolgálólányok testvériségéről és a politika színfalai mögötti életről."),
dict(title="Queen's Hope", hu=None, type="novel", canon=True, rel="2022-01-25", y=-22.05,
     wook="Queen's Hope",
     desc="A Queen-trilógia zárása: a frissen, titokban férjhez ment Padmé a klónháború kitörésének napjaiban kémküldetést vállal, míg Sabé a helyét veszi át a szenátusban."),
dict(title="Brotherhood", hu=None, type="novel", canon=True, rel="2022-05-10", y=-21.95,
     wook="Brotherhood (novel)",
     desc="Mike Chen regénye a klónháború első heteiből: a Cato Neimoidián történt merénylet ügyében Obi-Wan nyomoz, miközben ő és a frissen lovaggá ütött Anakin megtanulnak immár egyenrangú társakként — testvérekként — együtt harcolni."),
dict(title="Thrawn Ascendancy: Chaos Rising", hu=None, type="novel", canon=True, rel="2020-09-01", y=-19.45,
     wook="Thrawn Ascendancy: Chaos Rising",
     desc="Timothy Zahn trilógiájának nyitánya a galaxison túli Chiss Birodalomból: a fiatal Thrawn felemelkedése saját népe flottájában, még a Birodalommal való találkozása előtt."),
dict(title="Dark Disciple", hu=None, type="novel", canon=True, rel="2015-07-07", y=-19.4,
     wook="Dark Disciple",
     desc="A Klónok háborúja el nem készült epizódjaiból írt regény: a jedik Quinlan Vost bízzák meg Dooku gróf meggyilkolásával — társa pedig nem más, mint az egykori Sith-tanítvány, Asajj Ventress. Sötét, felnőtt hangvételű történet áldozatról és megváltásról."),
dict(title="Star Wars Outlaws: Low Red Moon", hu=None, type="novel", canon=True, rel="2026-02-03", y=-19.2,
     wook="Star Wars Outlaws: Low Red Moon",
     desc="A Star Wars Outlaws játékhoz kapcsolódó 2026-os előzményregény a klónháborúk korából, amely a játék világának alvilági szereplőihez vezet vissza."),
# ---- Reign of the Empire ----
dict(title="Reign of the Empire: The Mask of Fear", hu=None, type="novel", canon=True, rel="2025-02-25", y=-18.95, era="reign",
     wook="Reign of the Empire: The Mask of Fear",
     desc="Az új Birodalom-trilógia nyitánya a Sith-ek bosszúja utáni hetekből: Mon Mothma, Bail Organa és Saw Gerrera három különböző úton próbál szembenézni azzal, hogy a demokrácia tapsvihar közepette halt meg."),
dict(title="Master of Evil", hu=None, type="novel", canon=True, rel="2025-11-11", y=-18.85, era="reign",
     wook="Master of Evil",
     desc="Adam Christopher Vader-regénye a Birodalom hajnaláról: a frissen páncélba zárt Sith nagyúr első évei, amikor a gyász és a gyűlölet még nyers erővel formálja a galaxis új rémét."),
dict(title="Thrawn Ascendancy: Greater Good", hu=None, type="novel", canon=True, rel="2021-04-27", y=-18.7, era="reign",
     wook="Thrawn Ascendancy: Greater Good",
     desc="A Chiss-trilógia középső kötete: Thrawn ellenfelei már nem flottákkal, hanem szavakkal és családi intrikákkal támadnak — a Chiss Birodalom belülről kezd repedezni."),
dict(title="Thrawn Ascendancy: Lesser Evil", hu=None, type="novel", canon=True, rel="2021-11-16", y=-18.6, era="reign",
     wook="Thrawn Ascendancy: Lesser Evil",
     desc="A trilógia zárása: Thrawn végső játszmája a Chiss Birodalom megmentéséért — és a döntés, amely a száműzetéséhez, a Birodalomhoz és a Star Wars Rebelsig vezető úthoz vezet."),
dict(title="Sanctuary", hu=None, type="novel", canon=True, rel="2025-08-05", y=-18, era="reign",
     wook="Sanctuary (novel)",
     desc="2025-ös kánonregény a birodalmi éra elejéről: menedéket kereső túlélők története a formálódó elnyomás árnyékában."),
dict(title="Ahsoka", hu="Ahsoka", type="novel", canon=True, rel="2016-10-11", y=-17.8, era="reign",
     wook="Ahsoka (novel)",
     desc="E. K. Johnston regénye a 66-os parancs után bujkáló Ahsoka Tanóról: a Raada holdján új életet kezdene, de a Birodalom megjelenése ismét harcra — és a Fulcrum-szerep vállalására — kényszeríti."),
dict(title="Catalyst: A Rogue One Novel", hu="Katalizátor", type="novel", canon=True, rel="2016-11-15", y=-17, era="reign",
     wook="Catalyst: A Rogue One Novel",
     desc="A Zsivány Egyes előzményregénye: Galen Erso és Orson Krennic évtizedes játszmája, amelynek tétje a Halálcsillag szuperlézere — és az Erso család sorsa."),
dict(title="Thrawn", hu="Thrawn", type="novel", canon=True, rel="2017-04-11", y=-15, era="reign",
     wook="Thrawn (novel)",
     desc="Timothy Zahn újraírt eredettörténete a kánonban: a száműzött chiss stratéga szédületes karrierje a birodalmi flottában, kadéttól a főadmirálisi rangig — oldalán Eli Vantóval."),
dict(title="Lords of the Sith", hu="A Sith nagyurak", type="novel", canon=True, rel="2015-04-28", y=-14, era="reign",
     wook="Lords of the Sith",
     desc="Az Uralkodó és Vader hajója lezuhan a Ryloth felett, ahol Cham Syndulla felkelői vadásznak rájuk — ritka alkalom, amikor a két Sith nagyurat együtt, akcióban látjuk."),
dict(title="Tarkin", hu="Tarkin", type="novel", canon=True, rel="2014-11-04", y=-13.9, era="reign",
     wook="Tarkin (novel)",
     desc="James Luceno portréregénye a Birodalom leghidegebb elméjéről: Wilhuff Tarkin felemelkedése, neveltetése és a doktrína, amely a Halálcsillagig vezet."),
dict(title="Inquisitor: Rise of the Red Blade", hu=None, type="novel", canon=True, rel="2023-07-18", y=-13.5, era="reign",
     wook="Inquisitor: Rise of the Red Blade",
     desc="Egy jedi lovagból lett inkvizítor története belülről: Iskat Akaris útja a rend bukásától a vörös pengéig — a sötét oldal lélektani rajza."),
dict(title="Most Wanted", hu=None, type="novel", canon=True, rel="2018-05-25", y=-13, era="reign",
     wook="Most Wanted",
     desc="A Solo előzménye: a tinédzser Han és Qi'ra még riválisként róják a Corellia utcáit, amikor egy balul sikerült üzlet közös menekülésre kényszeríti őket."),
dict(title="Star Wars Jedi: Battle Scars", hu=None, type="novel", canon=True, rel="2023-03-07", y=-11.2, era="reign",
     wook="Star Wars Jedi: Battle Scars",
     desc="A Fallen Order és a Survivor közti évekből: Cal Kestis és a Mantis legénysége egy szökött rohamosztagos oldalán vállal veszélyes küldetést — a játékok rajongóinak kötelező."),
dict(title="Crimson Climb", hu=None, type="novel", canon=True, rel="2023-10-10", y=-11, era="reign",
     wook="Crimson Climb",
     desc="Qi'ra útja a corelliai csatornáktól a Crimson Dawn belső köréig: E. K. Johnston ifjúsági regénye a túlélésről és az árról, amit a hatalomért fizetni kell."),
dict(title="A New Dawn", hu="Új hajnal", type="novel", canon=True, rel="2014-09-02", y=-10.8, era="reign",
     wook="A New Dawn",
     desc="Az új kánon első regénye: Kanan Jarrus és Hera Syndulla első találkozása a Gorse bolygón — a Rebels-legénység születése, John Jackson Miller tollából."),
dict(title="Rebel Rising", hu=None, type="novel", canon=True, rel="2017-05-02", y=-8, era="reign",
     wook="Rebel Rising",
     desc="Jyn Erso elveszett évei: Saw Gerrera neveltjeként partizánná válik, majd magára marad — az ifjúsági regény a Zsivány Egyes hősnőjének sebeit mutatja meg."),
dict(title="Lost Stars", hu="Elveszett csillagok", type="novel", canon=True, rel="2015-09-04", y=-6, era="reign",
     wook="Lost Stars",
     desc="Claudia Gray rajongói kedvence: két gyerekkori jóbarát — egy birodalmi tiszt és egy lázadó pilóta — szerelme, miközben a galaktikus polgárháború ellentétes oldalaira sodródnak, a Jakku csatájáig."),
dict(title="Reign of the Empire: Edge of the Abyss", hu=None, type="novel", canon=True, rel="2026-09-15", y=-5.9, era="reign", upcoming=True,
     wook="Reign of the Empire: Edge of the Abyss",
     desc="A Birodalom-trilógia 2026 szeptemberében érkező középső kötete: a Mask of Fear szereplői tovább csúsznak a nyílt ellenállás — vagy a behódolás — felé."),
# ---- Age of Rebellion ----
dict(title="Leia, Princess of Alderaan", hu="Leia, Alderaan hercegnője", type="novel", canon=True, rel="2017-09-01", y=-3,
     wook="Leia, Princess of Alderaan",
     desc="A tizenhat éves Leia Organa beavatása: miközben trónörökösi próbáit teljesíti, rájön, hogy szülei titokban lázadást szerveznek — Claudia Gray ifjúsági regénye, amelyben Amilyn Holdo is feltűnik."),
dict(title="Thrawn: Alliances", hu="Thrawn: Szövetségek", type="novel", canon=True, rel="2018-07-24", y=-2,
     wook="Thrawn: Alliances",
     desc="Két idősík, két szövetség: Thrawn és Vader közös birodalmi küldetése — párhuzamosan azzal, amikor a klónháborúban Thrawn még Anakin Skywalkerrel találkozott."),
dict(title="Thrawn: Treason", hu="Thrawn: Árulás", type="novel", canon=True, rel="2019-07-23", y=-1.2,
     wook="Thrawn: Treason",
     desc="A Thrawn-trilógia zárása: a főadmirális a Halálcsillag-projekt árnyékában manőverezik a birodalmi udvari intrikák és a chiss lojalitás között — közvetlenül a Rebels fináléja előtt."),
dict(title="Battlefront II: Inferno Squad", hu="Battlefront II: Inferno osztag", type="novel", canon=True, rel="2017-07-19", y=0.2,
     wook="Battlefront II: Inferno Squad",
     desc="A Battlefront II játék előzménye: közvetlenül a Halálcsillag pusztulása után Iden Versio elit osztaga beépül a Saw Gerrera-féle partizánok maradékai közé."),
dict(title="Heir to the Jedi", hu="A Jedi örököse", type="novel", canon=True, rel="2015-03-03", y=0.4,
     wook="Heir to the Jedi",
     desc="Egyes szám első személyű Luke-regény a yavini csata utáni hónapokból: a fiatal hős mester nélkül, magában próbálja megérteni az Erőt egy veszélyes mentőakció közben."),
dict(title="Battlefront: Twilight Company", hu="Battlefront: Alkony század", type="novel", canon=True, rel="2015-11-03", y=3.1,
     wook="Battlefront: Twilight Company",
     desc="A lázadás gyalogságának háborús regénye: a 61-es mobil gyalogság, az Alkony század visszavonulása és helytállása a Hoth utáni sötét hónapokban — nyers, katonai nézőpontú Star Wars."),
# ---- New Republic ----
dict(title="The Princess and the Scoundrel", hu=None, type="novel", canon=True, rel="2022-08-16", y=4.3,
     wook="The Princess and the Scoundrel",
     desc="Han és Leia esküvője és mézeshetei — közvetlenül az endori győzelem után, egy luxus-űrhajón, ahol a Birodalom árnyéka a nászútra is elér."),
dict(title="Aftermath", hu="Utóhatás", type="novel", canon=True, rel="2015-09-04", y=4.4,
     wook="Aftermath (novel)",
     desc="Chuck Wendig trilógiájának nyitánya az endori csata után: a Birodalom szétesőben, az Új Köztársaság születőben — Norra Wexley és csapata birodalmi főtiszteket vadászik az Akiva felett."),
dict(title="Alphabet Squadron", hu=None, type="novel", canon=True, rel="2019-06-11", y=4.5,
     wook="Alphabet Squadron",
     desc="Öt pilóta, ötféle vadászgép, egy közös trauma: az Alexander Freed-trilógia a polgárháború utolsó felvonásának lélektani háborús regénye, a Shadow Wing birodalmi ászai ellen."),
dict(title="Aftermath: Life Debt", hu="Utóhatás: Életadósság", type="novel", canon=True, rel="2016-07-12", y=5.0,
     wook="Aftermath: Life Debt",
     desc="A trilógia középső kötete: Han Solo és Csubakka a Kashyyyk felszabadítására indul, míg Norráék a szökésben lévő Rae Sloane admirálist üldözik."),
dict(title="Shadow Fall: An Alphabet Squadron Novel", hu=None, type="novel", canon=True, rel="2020-06-23", y=5.1,
     wook="Shadow Fall",
     desc="Az Alphabet Squadron folytatása: csapda a Cerberon-rendszerben, ahol Yrica Quell múltja utoléri a századot — a trilógia legsötétebb kötete."),
dict(title="Aftermath: Empire's End", hu="Utóhatás: A Birodalom vége", type="novel", canon=True, rel="2017-02-21", y=5.3,
     wook="Aftermath: Empire's End",
     desc="A Birodalom végnapjai: minden szál a Jakku sivatagbolygója felé fut, ahol a birodalmi flotta maradéka megvívja az utolsó, megsemmisítő csatát az Új Köztársasággal."),
dict(title="Victory's Price: An Alphabet Squadron Novel", hu=None, type="novel", canon=True, rel="2021-03-02", y=5.4,
     wook="Victory's Price",
     desc="A trilógia fináléja: az Alphabet század a jakkui végjáték felé sodródik, ahol a bosszú és a megbocsátás közt kell választani — méltó zárása az új kánon legjobb regényfolyamának."),
dict(title="Last Shot", hu=None, type="novel", canon=True, rel="2018-04-17", y=7,
     wook="Last Shot",
     desc="Han Solo és Lando Calrissian közös kalandja több idősíkon: egy droidokat fanatizáló őrült terve ellen a régi csirkefogóknak ismét össze kell állniuk — pár évvel az endori csata után."),
dict(title="Poe Dameron: Free Fall", hu=None, type="novel", canon=True, rel="2020-08-04", y=19,
     wook="Poe Dameron: Free Fall",
     desc="A tinédzser Poe Dameron elszökik a Yavin 4-ről, és a hírhedt Zsinór-fűszercsempészek közé keveredik — itt derül ki, honnan ismeri Zorii Blisst és a Kijimit."),
dict(title="Shadow of the Sith", hu=None, type="novel", canon=True, rel="2022-06-28", y=21,
     wook="Shadow of the Sith",
     desc="A Skywalker kora előzményeit feltáró regény: Luke Skywalker és Lando Calrissian a Sith-ek exegoli árnyát kutatja, miközben a kis Rey szülei menekülnek a múlt elől."),
dict(title="Bloodline", hu="Vérvonal", type="novel", canon=True, rel="2016-05-03", y=28, era="newrepublic",
     wook="Bloodline (novel)",
     desc="Claudia Gray politikai drámája hat évvel Az ébredő Erő előtt: Leia szenátori karrierje összeomlik, amikor a galaxis megtudja, ki volt az apja — és megszületik az Ellenállás gondolata."),
# ---- Rise of the First Order ----
dict(title="Force Collector", hu=None, type="novel", canon=True, rel="2019-10-04", y=32, era="firstorder",
     wook="Force Collector",
     desc="Egy Erő-érzékeny tinédzser, Karr Nuq Sin ereklyék érintésén keresztül látja a jedik múltját — ifjúsági regény, amely az ébredő Erő előestéjén kutatja, mi maradt a jedi örökségből."),
dict(title="Eyes Like Stars", hu=None, type="novel", canon=True, rel="2026-07-21", y=33, era="firstorder",
     wook="Eyes Like Stars",
     desc="Ashley Poston ifjúsági románca: a coruscanti csillagtúra-hajón dolgozó, tizennyolc éves Ardent Quay megmenti egy titokzatos Vad Űrjáró életét, aki ezután potyautasként a fedélzeten marad. Egy rejtélyes ereklye és az Első Rend is a nyomukba ered."),
dict(title="Phasma", hu="Phasma", type="novel", canon=True, rel="2017-09-01", y=33.9, era="firstorder",
     wook="Phasma (novel)",
     desc="A krómpáncélos kapitány eredettörténete: Phasma útja a posztapokaliptikus Parnassos pusztaságaitól az Első Rend elitjéig — egy fogoly vallomásán keresztül elmesélve."),
dict(title="Galaxy's Edge: Black Spire", hu=None, type="novel", canon=True, rel="2019-08-27", y=34.4, era="firstorder",
     wook="Galaxy's Edge: Black Spire",
     desc="Az Ellenállás kémje, Vi Moradi a Batuu Fekete Csúcs előőrsén szervez sejtet az Első Rend ellen — a Galaxy's Edge park világát megalapozó regény."),
dict(title="A Crash of Fate", hu=None, type="novel", canon=True, rel="2019-08-06", y=34.45, era="firstorder",
     wook="A Crash of Fate",
     desc="Két gyerekkori barát találkozik újra a Batuun egy sorsfordító nap alatt — ifjúsági regény a Galaxy's Edge világából."),
dict(title="Resistance Reborn", hu=None, type="novel", canon=True, rel="2019-11-05", y=34.42, era="firstorder",
     wook="Resistance Reborn",
     desc="Az utolsó Jedik és a Skywalker kora közti híd: a crait-i vereség után Leia, Poe és a maroknyi túlélő szövetségeseket gyűjt a galaxisban az utolsó felvonáshoz."),
# ---- New Jedi Order ----
dict(title="The Last Order", hu=None, type="novel", canon=True, rel="2025-10-21", y=35.45, era="newjedi",
     wook="The Last Order",
     desc="Kwame Mbalia 2025-ös ifjúsági regénye közvetlenül a Skywalker kora után: az Ellenállás egy hajónyi, az Első Rend által elrabolt fiatalt ment meg — az újjáépítés korszakának első története."),
]

COMICS = [
dict(title="Star Wars: The High Republic (Marvel)", hu=None, type="comic", canon=True, rel="2021-01-06", y=-231.8,
     wook="Star Wars: The High Republic",
     desc="A High Republic-kezdeményezés fő képregénysorozata: Keeve Trennis jedi lovag kalandjai a Csillagfény Jelzőfényen és azon túl — mindhárom fázison átívelő Marvel-széria."),
dict(title="Star Wars: The High Republic Adventures", hu=None, type="comic", canon=True, rel="2021-02-03", y=-231.7,
     wook="Star Wars: The High Republic Adventures, Volume One",
     desc="A Főkorszak ifjúsági képregénysorozata: padawanok és fiatal jedik a Nihil-válság sűrűjében — előbb az IDW, majd a Dark Horse gondozásában."),
dict(title="Darth Maul (2017)", hu=None, type="comic", canon=True, rel="2017-02-01", y=-33,
     wook="Star Wars: Darth Maul (2017)",
     desc="A Baljós árnyak előtt: a türelmetlen Sith-tanítvány titokban jedi vérre szomjazik, és egy elrabolt padawan nyomába ered — Maul első kánon-minisorozata."),
dict(title="Obi-Wan & Anakin", hu=None, type="comic", canon=True, rel="2016-01-06", y=-30,
     wook="Star Wars: Obi-Wan and Anakin",
     desc="Charles Soule minisorozata a ritkán látott időszakból: a padawan Anakin és mestere egy elszigetelt, háborúba fagyott bolygón ragad — miközben Palpatine már szövögeti hálóját a fiú körül."),
dict(title="Jedi of the Republic – Mace Windu", hu=None, type="comic", canon=True, rel="2017-08-30", y=-21.9,
     wook="Star Wars: Jedi of the Republic – Mace Windu",
     desc="Mace Windu a klónháború első heteiben: a jedi tábornokká válás dilemmái egy dzsungelbolygón vívott küldetésen."),
dict(title="Kanan: The Last Padawan", hu=None, type="comic", canon=True, rel="2015-04-01", y=-19.1, era="reign",
     wook="Star Wars: Kanan",
     desc="Hogyan lett a padawan Caleb Dume-ból Kanan Jarrus: a 66-os parancs túlélése, menekülés és újjászületés — a Rebels rajongóinak alapmű."),
dict(title="Darth Vader: Dark Lord of the Sith (2017)", hu=None, type="comic", canon=True, rel="2017-06-07", y=-18.98, era="reign",
     wook="Darth Vader: Dark Lord of the Sith",
     desc="Charles Soule sorozata Vader első lépéseiről: a vörös kristály megtörése, az inkvizítorok kiképzése és a jedik levadászása — sokak szerint a legjobb kánon Star Wars-képregény."),
dict(title="Obi-Wan (2022)", hu=None, type="comic", canon=True, rel="2022-05-04", y=-8.5, era="reign",
     wook="Star Wars: Obi-Wan (comic series)",
     desc="A tatuini remete naplója: Obi-Wan életének öt korszaka öt füzetben, az ifjonc évektől a sivatagi magányig."),
dict(title="Princess Leia (2015)", hu=None, type="comic", canon=True, rel="2015-03-04", y=0.15,
     wook="Star Wars: Princess Leia",
     desc="Közvetlenül a yavini csata után: Leia az Alderaan szétszóródott túlélőit gyűjti össze a galaxisból, mielőtt a Birodalom végezne velük."),
dict(title="Star Wars (2015)", hu=None, type="comic", canon=True, rel="2015-01-14", y=0.3,
     wook="Star Wars (2015)",
     desc="A Marvel visszatérésének zászlóshajója: Luke, Leia és Han kalandjai az Egy új remény és A Birodalom visszavág között — 75 füzeten át, Vader elleni macska-egér játékkal."),
dict(title="Darth Vader (2015)", hu=None, type="comic", canon=True, rel="2015-02-11", y=0.35,
     wook="Darth Vader (2015)",
     desc="Kieron Gillen sorozata a Halálcsillag elvesztése után kegyvesztett Vaderről, aki saját titkos játszmába kezd — itt debütál a rajongói kedvenc gonosz droidpáros, a BT-1 és a 0-0-0, valamint Doctor Aphra."),
dict(title="Star Wars: Vader Down", hu=None, type="comic", canon=True, rel="2015-11-18", y=0.45,
     wook="Vader Down",
     desc="A Star Wars és a Darth Vader sorozatok első nagy crossovere: Vader gépe lezuhan a Vrogas Vason, és a teljes lázadó flotta rárontja magát — ő pedig egymaga áll ki egy hadsereg ellen."),
dict(title="The Screaming Citadel", hu=None, type="comic", canon=True, rel="2017-05-10", y=0.48,
     wook="The Screaming Citadel",
     desc="Gótikus horror-crossover: Luke és Doctor Aphra egy vámpírkirálynő fellegvárába merészkedik, hogy megfejtsen egy ősi jedi ereklyét."),
dict(title="Doctor Aphra (2016)", hu=None, type="comic", canon=True, rel="2016-12-07", y=1.0,
     wook="Star Wars: Doctor Aphra (2016)",
     desc="Az új kánon legnépszerűbb saját karaktere: a gátlástalan régészdoktornő, Aphra túlélni próbálja saját átveréseit — morálisan romlott, zseniálisan szórakoztató sorozat."),
dict(title="Star Wars (2020)", hu=None, type="comic", canon=True, rel="2020-01-01", y=3.35,
     wook="Star Wars (2020)",
     desc="A Birodalom visszavág utáni hónapok: a szétvert lázadó flotta újjászervezése, Luke a fénykardja és önmaga keresésében — a Marvel-főcím második nagy korszaka."),
dict(title="Darth Vader (2020)", hu=None, type="comic", canon=True, rel="2020-02-05", y=3.4,
     wook="Darth Vader (2020)",
     desc="Greg Pak sorozata: a „Nem én vagyok az apád” elhangzása után Vader Padmé múltjának nyomába ered — az út az Exegolig és a Skywalker kora előzményeiig vezet."),
dict(title="Bounty Hunters (2020)", hu=None, type="comic", canon=True, rel="2020-03-11", y=3.5,
     wook="Star Wars: Bounty Hunters",
     desc="Boba Fett, Bossk, Valance és a galaxis legveszélyesebb fejvadászai egy régi árulás szálait varrják el — hosszan futó sorozat a Birodalom visszavág utáni alvilágból."),
dict(title="War of the Bounty Hunters", hu=None, type="comic", canon=True, rel="2021-05-05", y=3.6,
     wook="War of the Bounty Hunters",
     desc="Nagyszabású crossover-esemény: Boba Fett elveszíti a karbonitba fagyasztott Han Solót, akiért az egész alvilág — és a Crimson Dawn — versenybe száll."),
dict(title="Crimson Reign", hu=None, type="comic", canon=True, rel="2021-12-08", y=3.7,
     wook="Crimson Reign",
     desc="A Qi'ra vezette Crimson Dawn nyílt háborút hirdet a Sith-ek uralma ellen — a Soule-féle crossover-trilógia középső felvonása."),
dict(title="Hidden Empire", hu=None, type="comic", canon=True, rel="2022-11-16", y=3.8,
     wook="Hidden Empire",
     desc="A trilógia zárása: Qi'ra végső terve az Uralkodó és Vader ellen egy ősi Sith-rituálé körül forog — a kimenetele visszhangzik a Jedi visszatérig."),
dict(title="Shattered Empire", hu=None, type="comic", canon=True, rel="2015-09-09", y=4.35,
     wook="Shattered Empire",
     desc="Az endori győzelem másnapja: Poe Dameron szülei, Shara Bey és Kes Dameron az Uralkodó posztumusz bosszúhadjárata ellen harcolnak — az első „Journey to The Force Awakens” történet."),
dict(title="Star Wars: Battle of Jakku", hu=None, type="comic", canon=True, rel="2024-10-02", y=4.9,
     wook="Star Wars: Battle of Jakku",
     desc="2024-25-ös crossover-trilógia, amely végre képregényben meséli el a galaktikus polgárháború utolsó nagy csatáját és a Birodalom kapitulációját."),
dict(title="The Rise of Kylo Ren", hu=None, type="comic", canon=True, rel="2019-12-18", y=28.4, era="firstorder",
     wook="Star Wars: The Rise of Kylo Ren",
     desc="Ben Solo bukása: a jedi templom leégésének éjszakája, menekülés a Ren lovagjaihoz — Charles Soule minisorozata megmutatja, hogyan született Kylo Ren."),
dict(title="Poe Dameron (2016)", hu=None, type="comic", canon=True, rel="2016-04-06", y=33.4, era="firstorder",
     wook="Star Wars: Poe Dameron",
     desc="A Fekete Század akcióban: Poe és pilótái Lor San Tekka nyomát kutatják az Első Rend orra előtt — a sorozat egyenesen Az ébredő Erő nyitányába torkollik."),
dict(title="Captain Phasma", hu=None, type="comic", canon=True, rel="2017-09-06", y=34.25, era="firstorder",
     wook="Star Wars: Captain Phasma",
     desc="Hogyan mászott ki Phasma a szemétledobóból a Starkiller bázis pusztulásakor — és hogyan tüntette el az árulásának nyomait: minisorozat a két sequel-film között."),
dict(title="Star Wars: Legacy of Vader", hu=None, type="comic", canon=True, rel="2025-02-05", y=34.48, era="firstorder",
     wook="Star Wars: Legacy of Vader",
     desc="2025 nagy Marvel-sorozata: az immár Legfőbb Vezér Kylo Ren nagyapja örökségének nyomába ered a Mustafartól a birodalmi múlt romjaiig — Charles Soule visszatérése a karakterhez."),
]
